title: Srikanth Chakravarthy
description: Srikanth is a Software Engineer. He is now studying "Machine Learning" and creating projects related to his studies.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

