title: Srikanth Chakravarthy
description: Srikanth is a Software Engineer. He is now studying "Machine Learning" and creating projects related to his studies.
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/scorsagg/">LinkedIn</a> |
  <a href="https://github.com/scorsagg">GitHub</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
